# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coastguard < Formula
  desc "Coastguard CLI — manage your coasts.dev projects"
  homepage "https://coasts.dev"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.3/coastguard-darwin-amd64"
      sha256 "7d2f9ed326c7aad837511709970a3f02d29354c520186891269ae96e29865402"

      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.3/coastguard-darwin-arm64"
      sha256 "6104ef5368fbdc4fdb2a172e182479201fcdc6231983ee0cf117acd692058d07"

      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.3/coastguard-linux-amd64"
      sha256 "c87e741699d75701c82b2bf654700d8fe8ca2e5ab3ff8d2f1c988ed418c01232"
      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.3/coastguard-linux-arm64"
      sha256 "3c4088b3bf2d212f204bae44d2e92014bcd1e257121dcc33ea74e04f1af5b526"
      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
  end

  test do
    assert_match "coastguard", shell_output("#{bin}/coastguard --version")
  end
end
