# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coastguard < Formula
  desc "Coastguard CLI — manage your coasts.dev projects"
  homepage "https://coasts.dev"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.1/coastguard-darwin-amd64"
      sha256 "7eea72a582551b8a569de8e4f247edeb5b32379d58cdf91150f63f42bcfe69f4"

      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.1/coastguard-darwin-arm64"
      sha256 "819b7fbda36363adb62ed3df4d4c5cd0e023c2348dd174a555800a012bcc6f1c"

      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.1/coastguard-linux-amd64"
      sha256 "39a788d4377832c606b74445999185ee7a30355ce51d608cc2aefa2139046392"
      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsx-tool/coast-cli/releases/download/v0.0.1/coastguard-linux-arm64"
      sha256 "b60e7936dd668ac78d5697058ce612add4bf0ffa8449e719b9a16676c027d270"
      define_method(:install) do
        bin.install Dir["coastguard*"].first => "coastguard"
      end
    end
  end

  test do
    assert_match "coastguard", shell_output("#{bin}/coastguard --version")
  end
end
